name: Generate Pacman Contribution Graph

on:
  schedule:
    - cron: "0 0 * * *"  # Runs every day at midnight UTC
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    name: Generate SVG
    steps:
      - uses: actions/checkout@v3

      - name: Generate Pacman SVG
        uses: Platane/snk@v3
        with:
          github_user_name: SRx210
          outputs: |
            ./output/pacman-contribution-graph.svg
            ./output/pacman-contribution-graph-dark.svg
          theme: pacman

      - name: Commit and Push
        uses: EndBug/add-and-commit@v9
        with:
          message: "Generated Pacman contribution graph"
          add: "output/*.svg"
